### ISSUE TITLE
Adding NavigationAgent crashes Engine

### ISSUE THREAD

**Issue by Duroxxigar** [AndreaCatania/godot#7]
**Godot version:**
Built from branch **nav_pr**

**OS/device including version:**
Windows 10

**Issue description:**
When adding a NavigationAgent node - the engine crashes

**Steps to reproduce:**
Add a NavigationAgent node. I originally thought that it might just be because I was adding it as a root node, but even as a child of Spatial, it crashed.

**Minimal reproduction project:**
No need to attach - it was a completely blank project.

**Comment by Duroxxigar** [comment]
![image](https://user-images.githubusercontent.com/16636969/71756533-5e2c8180-2e5e-11ea-82a8-1d4893928fbf.png)

**Comment by AndreaCatania** [comment]
Thanks for this, I've fixed this issue.
